// Auto-generated by scripts/generate_colorbars.py — do not edit manually.
// Re-run `make colorbars` if data/colorbars/*.csv files change.

export interface ColorbarsEntry { vmin: number; vmax: number }
export type ColorbarsGran = 'year' | 'month'
export type ColorbarsUnit = 'kg' | 'mm'

// COLORBAR_PRESETS[varName][gran][unit] → { vmin, vmax }
// gran: 'year' for yearly/avg_yearly modes; 'month' for monthly/avg_monthly modes.
// unit: 'mm' when isKgToMm && var.units === 'kg'; 'kg' otherwise.
// avg_season mode always uses auto range — do not look up here.
export const COLORBAR_PRESETS: Record<string, Record<ColorbarsGran, Record<ColorbarsUnit, ColorbarsEntry>>> = {
  CEv: {
    year: {
      kg: { vmin: 0.7004807375134849, vmax: 4.931703835968852 },
      mm: { vmin: 0.7004807375134849, vmax: 4.931703835968852 },
    },
    month: {
      kg: { vmin: 0.2710139609622161, vmax: 5.251322922385454 },
      mm: { vmin: 0.2710139609622161, vmax: 5.251322922385454 },
    },
  },
  CWR: {
    year: {
      kg: { vmin: 7648160607053.291, vmax: 16234676014040.717 },
      mm: { vmin: 729.566307309836, vmax: 1561.8636192093925 },
    },
    month: {
      kg: { vmin: 364255934511.6571, vmax: 1666549273838.3516 },
      mm: { vmin: 34.42092066237925, vmax: 161.04797108328864 },
    },
  },
  GMh: {
    year: {
      kg: { vmin: 11124162254339.244, vmax: 28356682151089.332 },
      mm: { vmin: 1099.6817650701853, vmax: 2615.220964945392 },
    },
    month: {
      kg: { vmin: 436592878139.65344, vmax: 3164478183805.2295 },
      mm: { vmin: 41.57968999073379, vmax: 294.9508822291398 },
    },
  },
  GMv: {
    year: {
      kg: { vmin: 132592523057233.8, vmax: 752626810772125.2 },
      mm: { vmin: 12826.912405802186, vmax: 68082.61397594532 },
    },
    month: {
      kg: { vmin: 7285364657766.795, vmax: 56179921501088.164 },
      mm: { vmin: 713.137221492175, vmax: 5151.05127413799 },
    },
  },
  INh: {
    year: {
      kg: { vmin: 7267932221920.2295, vmax: 15600533278979.914 },
      mm: { vmin: 692.5613812154397, vmax: 1495.3514300803688 },
    },
    month: {
      kg: { vmin: 329667027360.4858, vmax: 1600108892305.1047 },
      mm: { vmin: 31.077317910368784, vmax: 154.58732790171246 },
    },
  },
  INv: {
    year: {
      kg: { vmin: 130257413745013.67, vmax: 741848261958317.4 },
      mm: { vmin: 12594.485881312072, vmax: 67164.2733897736 },
    },
    month: {
      kg: { vmin: 7168406164226.914, vmax: 55432185554715.65 },
      mm: { vmin: 701.6166042592598, vmax: 5083.662854879697 },
    },
  },
  MC: {
    year: {
      kg: { vmin: 1505723276323.3428, vmax: 14470553351315.553 },
      mm: { vmin: 154.09034225171118, vmax: 1319.1727427954456 },
    },
    month: {
      kg: { vmin: 40051537007.180275, vmax: 1788853656030.884 },
      mm: { vmin: 3.9138008787083876, vmax: 165.83711130943888 },
    },
  },
  OTh: {
    year: {
      kg: { vmin: 7269382590864.5205, vmax: 15784298822697.814 },
      mm: { vmin: 691.8371138492794, vmax: 1519.1189877286884 },
    },
    month: {
      kg: { vmin: 332382417224.3518, vmax: 1620093628440.3389 },
      mm: { vmin: 31.407288937327237, vmax: 156.48571049735898 },
    },
  },
  OTv: {
    year: {
      kg: { vmin: 128805911103098.5, vmax: 735570132342910.2 },
      mm: { vmin: 12409.5322330707, vmax: 66501.23534606642 },
    },
    month: {
      kg: { vmin: 7150368615648.212, vmax: 54676841343066.65 },
      mm: { vmin: 699.6246486964711, vmax: 5017.994382786778 },
    },
  },
  PEh: {
    year: {
      kg: { vmin: 7.064923723848683, vmax: 54.38685963749987 },
      mm: { vmin: 7.064923723848683, vmax: 54.38685963749987 },
    },
    month: {
      kg: { vmin: 2.154761860418977, vmax: 58.82764949563064 },
      mm: { vmin: 2.154761860418977, vmax: 58.82764949563064 },
    },
  },
  RCh: {
    year: {
      kg: { vmin: 2.417667769275407, vmax: 20.612170963354878 },
      mm: { vmin: 2.417667769275407, vmax: 20.612170963354878 },
    },
    month: {
      kg: { vmin: 2.24991386415585, vmax: 54.46230747437197 },
      mm: { vmin: 2.24991386415585, vmax: 54.46230747437197 },
    },
  },
  RCv: {
    year: {
      kg: { vmin: 2.5835735562001916, vmax: 27.26354571901849 },
      mm: { vmin: 2.5835735562001916, vmax: 27.26354571901849 },
    },
    month: {
      kg: { vmin: 2.487544419371212, vmax: 90.34608517287458 },
      mm: { vmin: 2.487544419371212, vmax: 90.34608517287458 },
    },
  },
  SP: {
    year: {
      kg: { vmin: 887890223262.4321, vmax: 13718233141045.842 },
      mm: { vmin: 90.97993087768555, vmax: 1255.1162475585938 },
    },
    month: {
      kg: { vmin: 13615285038.565609, vmax: 1740589603546.1396 },
      mm: { vmin: 1.3493574976921086, vmax: 161.3879318237306 },
    },
  },
  aveMh: {
    year: {
      kg: { vmin: 1841870389.210707, vmax: 5296690522.590486 },
      mm: { vmin: 0.1806485112957689, vmax: 0.48255049284937046 },
    },
    month: {
      kg: { vmin: 709090499.9693445, vmax: 6294184106.82761 },
      mm: { vmin: 0.06744079611950637, vmax: 0.5875003625480198 },
    },
  },
  aveMv: {
    year: {
      kg: { vmin: 35248832464.160965, vmax: 343745305249.6325 },
      mm: { vmin: 3.4478008449299673, vmax: 31.079034246575386 },
    },
    month: {
      kg: { vmin: 14399601024.444485, vmax: 321280626428.3588 },
      mm: { vmin: 1.4014284036574614, vmax: 29.294687018156985 },
    },
  },
}
