"""
generate_colorbars.py
从 data/colorbars/ 下 4 个统计 CSV 生成 frontend/src/config/colorbars.ts。

用法（从项目根运行）：
    uv run --project scripts python scripts/generate_colorbars.py
或通过 Makefile：
    make colorbars

CSV 更新后须重跑本脚本并将生成的 colorbars.ts commit 到 git。
"""
import csv
import pathlib
import textwrap

# 系统当前支持的 15 个变量（与 frontend/src/config/vars.ts 保持一致）
SYSTEM_VARS = {
    "aveMh", "aveMv", "CEv", "CWR", "GMh", "GMv",
    "INh", "INv", "MC", "OTh", "OTv", "PEh", "RCh", "RCv", "SP",
}

# CSV 文件 → (粒度, 单位)
CSV_MAP = {
    "Year_Kg_values_maxmin_summary.csv":   ("year",  "kg"),
    "Year_mm_values_maxmin_summary.csv":   ("year",  "mm"),
    "month_Kg_values_maxmin_summary.csv":  ("month", "kg"),
    "month_mm_values_maxmin_summary.csv":  ("month", "mm"),
}

ROOT    = pathlib.Path(__file__).parent.parent
CSV_DIR = ROOT / "data" / "colorbars"
OUT     = ROOT / "frontend" / "src" / "config" / "colorbars.ts"


def load_presets() -> dict:
    result: dict = {}
    for fname, (gran, unit) in CSV_MAP.items():
        path = CSV_DIR / fname
        with open(path, newline="", encoding="utf-8-sig") as f:
            for row in csv.DictReader(f):
                var = row["varname"].strip()
                if var not in SYSTEM_VARS:
                    continue
                vmin = float(row["colorbar_min"])
                vmax = float(row["colorbar_max"])
                result.setdefault(var, {}).setdefault(gran, {})[unit] = (vmin, vmax)
    return result


def fmt_num(n: float) -> str:
    # 保留足够精度，避免科学计数法歧义
    return repr(n)


def render_ts(presets: dict) -> str:
    lines = [
        "// Auto-generated by scripts/generate_colorbars.py — do not edit manually.",
        "// Re-run `make colorbars` if data/colorbars/*.csv files change.",
        "",
        "export interface ColorbarsEntry { vmin: number; vmax: number }",
        "export type ColorbarsGran = 'year' | 'month'",
        "export type ColorbarsUnit = 'kg' | 'mm'",
        "",
        "// COLORBAR_PRESETS[varName][gran][unit] → { vmin, vmax }",
        "// gran: 'year' for yearly/avg_yearly modes; 'month' for monthly/avg_monthly modes.",
        "// unit: 'mm' when isKgToMm && var.units === 'kg'; 'kg' otherwise.",
        "// avg_season mode always uses auto range — do not look up here.",
        "export const COLORBAR_PRESETS: Record<string, Record<ColorbarsGran, Record<ColorbarsUnit, ColorbarsEntry>>> = {",
    ]
    for var in sorted(presets.keys()):
        lines.append(f"  {var}: {{")
        for gran in ("year", "month"):
            lines.append(f"    {gran}: {{")
            for unit in ("kg", "mm"):
                vmin, vmax = presets[var][gran][unit]
                lines.append(f"      {unit}: {{ vmin: {fmt_num(vmin)}, vmax: {fmt_num(vmax)} }},")
            lines.append("    },")
        lines.append("  },")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    presets = load_presets()
    missing = []
    for var in SYSTEM_VARS:
        for gran in ("year", "month"):
            for unit in ("kg", "mm"):
                if unit not in presets.get(var, {}).get(gran, {}):
                    missing.append(f"{var}/{gran}/{unit}")
    if missing:
        print("WARNING: missing entries:", missing)

    ts = render_ts(presets)
    OUT.write_text(ts, encoding="utf-8")
    print(f"Generated {OUT.relative_to(ROOT)} ({len(presets)} vars)")


if __name__ == "__main__":
    main()
